Init commit
oVirt/python-ovirt-engine-sdk4 pull request #1
Opened 2021-07-20 12:36 UTC by mnecas

First commit contains:
- automation for Jenkins
- sdk
- readme
- examples
- spec files
- tests

2021-07-20 12:42 UTC, mnecas commented
ci test please

2021-07-22 07:51 UTC, mwperina requested changes

2021-07-22 07:51 UTC, mwperina commented on pom.xml
pom.xml should be removed from the project, it should be contained only in the generator project

2021-07-22 07:51 UTC, mwperina commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should be removed completely

2021-07-30 04:59 UTC, mwperina approved these changes
+1

2021-07-30 11:46 UTC, merged