Migrate to sphinx
oVirt/python-ovirt-engine-sdk4 pull request #37
Opened 2022-01-10 11:37 UTC by oliel

2022-01-10 14:36 UTC, mwperina commented on .github/workflows/sphinx_doc.yaml
> +    - uses: ammaraskar/sphinx-action@master
Hmm, code in this action hasn't been changed for 2 years. Wouldn't it be better just run sphinx from command line? I mean replace pdoc invocation below with the relevant sphinx command?
https://github.com/oVirt/python-ovirt-engine-sdk4/blob/main/.github/workflows/create_docs.yaml#L53

2022-01-10 15:52 UTC, tinez reviewed
I don't see any changes to 'create_docs.yml' workflow, should we add the sphinx deps and run sphinx there?

2022-01-10 15:52 UTC, tinez commented on docs/source/conf.py
> +version = ''
Shouldn't we fill the version and release dynamically somehow (like by passing these as cmdline options to sphinx)

2022-01-10 15:52 UTC, tinez commented on docs/source/conf.py
> +     author, 'ovirtsdk4', 'One line description of project.',
Maybe we could change 'One line description of project' to something more meaningful

2022-01-11 12:42 UTC, mwperina requested changes

2022-01-11 12:42 UTC, mwperina commented on .github/workflows/create_docs.yaml
> +        run:
You have multiple commands executed so you need to use a pipe:

```
run: |
  cd ovirt-engine-sdk/docs
  make html
```

2022-01-11 13:10 UTC, mwperina reviewed
Try to change line 10 to:

```
workflow_dispatch:
  branches: [ master,sdk_4.4 ]
```

2022-01-18 09:03 UTC, closed without merging